/**
 * Wizard — DevOps scenario: scan org, detect custom catalog entries, generate yamls.
 *
 * All API calls are intercepted with mock responses — no real GitHub token needed.
 *
 * Run:
 *   cd klight-ui && npm run screenshots:wizard
 *   open tests/screenshots/wizard-devops/
 */

import { test, Page } from '@playwright/test';
import { waitForServer, screenshotStep } from './helpers';

const W = 'wizard-devops';

const MOCK_REPOS = [
  {
    name: 'inventory-api',
    description: 'FastAPI inventory microservice',
    has_klight: true, has_dockerfile: true, has_deploy_folder: false,
    url: 'https://github.com/slothlabsorg/inventory-api',
    is_service: true,
    unknown_needs: ['postgres-inventory'],
  },
  {
    name: 'store-api',
    description: 'FastAPI store + orders microservice',
    has_klight: true, has_dockerfile: true, has_deploy_folder: false,
    url: 'https://github.com/slothlabsorg/store-api',
    is_service: true,
    unknown_needs: ['postgres-store'],
  },
  {
    name: 'notification-service',
    description: 'Kafka consumer — sends email/SMS',
    has_klight: false, has_dockerfile: true, has_deploy_folder: false,
    url: 'https://github.com/slothlabsorg/notification-service',
    is_service: true,
    unknown_needs: [],
  },
  {
    name: 'store-web',
    description: 'Next.js storefront',
    has_klight: true, has_dockerfile: true, has_deploy_folder: false,
    url: 'https://github.com/slothlabsorg/store-web',
    is_service: true,
    unknown_needs: [],
  },
  {
    name: 'company-infra',
    description: 'K8s manifests and platform config',
    has_klight: false, has_dockerfile: false, has_deploy_folder: true,
    url: 'https://github.com/slothlabsorg/company-infra',
    is_service: false,
    unknown_needs: [],
  },
];

const MOCK_GENERATE = {
  catalog_warnings: [
    { repo: 'inventory-api', unknown_needs: ['postgres-inventory'] },
    { repo: 'store-api',     unknown_needs: ['postgres-store'] },
  ],
  results: [
    {
      repo: 'inventory-api', status: 'exists',
      yaml: `# yaml-language-server: $schema=https://slothlabsorg.github.io/klight/schema/klight.yaml.json
name: inventory-api
port: 8081
health: /health
image: ghcr.io/slothlabsorg/inventory-api:main
needs: [postgres-inventory, kafka, redis]
env:
  DATABASE_URL: "postgresql://inventory:inventorypass@postgres-inventory:5432/inventory_db"
  KAFKA_BROKERS: "kafka:9092"
`,
    },
    {
      repo: 'store-api', status: 'exists',
      yaml: `# yaml-language-server: $schema=https://slothlabsorg.github.io/klight/schema/klight.yaml.json
name: store-api
port: 8080
health: /health
image: ghcr.io/slothlabsorg/store-api:main
needs: [postgres-store, kafka]
env:
  DATABASE_URL: "postgresql+asyncpg://store:storepass@postgres-store:5432/store_db"
  KAFKA_BROKERS: "kafka:9092"
  INVENTORY_API_URL: "http://inventory-api:8081"
`,
    },
    {
      repo: 'notification-service', status: 'generated',
      yaml: `# yaml-language-server: $schema=https://slothlabsorg.github.io/klight/schema/klight.yaml.json
name: notification-service
port: 8082
health: /health
image: ghcr.io/slothlabsorg/notification-service:main

# Add infra needs (postgres, kafka, redis, localstack, etc.)
# needs: [postgres, kafka]

# Add env vars your code reads:
# env:
#   DB_HOST: postgres
`,
    },
    {
      repo: 'store-web', status: 'exists',
      yaml: `# yaml-language-server: $schema=https://slothlabsorg.github.io/klight/schema/klight.yaml.json
name: store-web
port: 80
health: /
image: ghcr.io/slothlabsorg/store-web:main
`,
    },
  ],
};

const MOCK_TEAM_YAML = {
  yaml: `# klight-team.yaml — generated by klight Setup Wizard
# yaml-language-server: $schema=https://slothlabsorg.github.io/klight/schema/klight-team.yaml.json
org: slothlabsorg
registry: ghcr.io/slothlabsorg

services:
  inventory-api:
    repo: https://github.com/slothlabsorg/inventory-api
    image: ghcr.io/slothlabsorg/inventory-api:main
  store-api:
    repo: https://github.com/slothlabsorg/store-api
    image: ghcr.io/slothlabsorg/store-api:main
  notification-service:
    repo: https://github.com/slothlabsorg/notification-service
    image: ghcr.io/slothlabsorg/notification-service:main
  store-web:
    repo: https://github.com/slothlabsorg/store-web
    image: ghcr.io/slothlabsorg/store-web:main

profiles:
  all:
    - inventory-api
    - store-api
    - notification-service
    - store-web
  backend:
    - inventory-api
    - store-api

url: https://raw.githubusercontent.com/slothlabsorg/company-infra/main/klight-team.yaml
`,
};

async function setupMocks(page: Page) {
  await page.route('/api/setup/scan', route =>
    route.fulfill({ json: { repos: MOCK_REPOS, total: MOCK_REPOS.length } })
  );
  await page.route('/api/setup/generate', route =>
    route.fulfill({ json: MOCK_GENERATE })
  );
  await page.route('/api/setup/team-yaml', route =>
    route.fulfill({ json: MOCK_TEAM_YAML })
  );
  await page.route('/api/setup/create-pr', route =>
    route.fulfill({ json: { ok: true, pr_url: 'https://github.com/slothlabsorg/notification-service/pull/12' } })
  );
}

test.beforeAll(async () => {
  await waitForServer({ page: null } as any, 'http://localhost:7700').catch(() => {});
});

test('01 — Setup Wizard tab (Step 1 — Platform & Access)', async ({ page }) => {
  await setupMocks(page);
  await page.goto('/');
  await page.waitForLoadState('networkidle');

  // Click Setup tab
  await page.locator('button', { hasText: /setup/i }).click();
  await page.waitForTimeout(300);

  // Pre-fill form
  await page.fill('#s-org', 'slothlabsorg');
  await page.fill('#s-token', 'ghp_••••••••••••••••••••••••••••••••••••••••');
  await page.fill('#s-registry', 'ghcr.io/slothlabsorg');

  await screenshotStep(page, W, '01-step1-platform-access');
});

test('02 — Step 2 — Repo list with catalog warnings', async ({ page }) => {
  await setupMocks(page);
  await page.goto('/');
  await page.waitForLoadState('networkidle');
  await page.locator('button', { hasText: /setup/i }).click();
  await page.waitForTimeout(300);

  await page.fill('#s-org', 'slothlabsorg');
  await page.fill('#s-token', 'ghp_••••••••••••••••••••••••••••••••••••••••');
  await page.fill('#s-registry', 'ghcr.io/slothlabsorg');

  await page.click('button:has-text("Scan repos")');
  await page.waitForSelector('#step2:not(.hidden)');
  await page.fill('#s-infra-repo', 'company-infra');
  await page.waitForTimeout(400);
  await page.locator('#step2').scrollIntoViewIfNeeded();

  await screenshotStep(page, W, '02-step2-repo-list-catalog-warnings', { fullPage: true });
});

test('03 — Step 3 — Review klight.yaml with catalog warning panel', async ({ page }) => {
  await setupMocks(page);
  await page.goto('/');
  await page.waitForLoadState('networkidle');
  await page.locator('button', { hasText: /setup/i }).click();
  await page.waitForTimeout(300);

  await page.fill('#s-org', 'slothlabsorg');
  await page.fill('#s-token', 'ghp_••••••••••••••••••••••••••••••••••••••••');
  await page.fill('#s-registry', 'ghcr.io/slothlabsorg');

  await page.click('button:has-text("Scan repos")');
  await page.waitForSelector('#step2:not(.hidden)');
  await page.waitForTimeout(300);

  // Ensure infra repo filled before generating
  await page.fill('#s-infra-repo', 'company-infra');
  await page.click('button:has-text("Generate klight.yaml")');
  await page.waitForSelector('#step3:not(.hidden)');
  await page.waitForTimeout(400);
  await page.locator('#step3').scrollIntoViewIfNeeded();
  await page.waitForTimeout(200);

  await screenshotStep(page, W, '03-step3-review-catalog-warning', { fullPage: true });
});

test('04 — Step 4 — klight-team.yaml + distribute', async ({ page }) => {
  await setupMocks(page);
  await page.goto('/');
  await page.waitForLoadState('networkidle');
  await page.locator('button', { hasText: /setup/i }).click();
  await page.waitForTimeout(300);

  await page.fill('#s-org', 'slothlabsorg');
  await page.fill('#s-token', 'ghp_••••••••••••••••••••••••••••••••••••••••');
  await page.fill('#s-registry', 'ghcr.io/slothlabsorg');

  await page.click('button:has-text("Scan repos")');
  await page.waitForSelector('#step2:not(.hidden)');
  await page.waitForTimeout(200);

  await page.fill('#s-infra-repo', 'company-infra');
  await page.click('button:has-text("Generate klight.yaml")');
  await page.waitForSelector('#step3:not(.hidden)');
  await page.waitForTimeout(200);

  await page.click('button:has-text("Generate klight-team.yaml")');
  await page.waitForSelector('#step4:not(.hidden)');
  await page.waitForTimeout(400);
  await page.locator('#step4').scrollIntoViewIfNeeded();
  await page.waitForTimeout(200);

  await screenshotStep(page, W, '04-step4-team-yaml-distribute', { fullPage: true });
});
