apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../../env/config
- ../../base

commonLabels:
  app: inventory-api

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: inventory-api-config
  envs:
  - config.env
  behavior: create
